---
services:
  redis:
    container_name: redis
    image: valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./favicon.ico:/usr/local/searxng/searx/static/favicon.ico:ro
      - ./custom_engines:/usr/share/searxng/engines
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      SEARXNG_BASE_URL: https://${SEARXNG_HOSTNAME}/
      UWSGI_WORKERS: ${SEARXNG_UWSGI_WORKERS:-4}
      UWSGI_THREADS: ${SEARXNG_UWSGI_THREADS:-4}
      SEARXNG_SETTINGS: |
        search:
          formats:
            - html
            - json
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
    command: ["/bin/sh", "-c", "apt-get update && apt-get install -y ca-certificates"]
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # 可选：添加以下字段避免 DNS 污染
    extra_hosts:
      - "www.google.com:31.13.88.169"
networks:
  searxng: 
volumes:
  valkey-data2: 

