---
services:
  redis:
    container_name: redis
    image: valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng:rw
      - ./favicon.ico:/usr/local/searxng/searx/static/favicon.ico:ro
    environment:
      SEARXNG_BASE_URL: https://${SEARXNG_HOSTNAME}/
      UWSGI_WORKERS: ${SEARXNG_UWSGI_WORKERS:-4}
      UWSGI_THREADS: ${SEARXNG_UWSGI_THREADS:-4}
      SEARXNG_SETTINGS: |
        search:
          formats:
            - html
            - json
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  searxng: 
volumes:
  valkey-data2: 

